tilesize = 32 

modsPath = '/mods'
mapsPath = '/maps'
soundPath = '/sounds'
tilesetsPath = '/tilesets'
gameStatesPath = '/gameStates'

[displayMode]

	displayWidth = 768		# 2^1 times the x resolution for best result
	displayHeight = 576 	# 2^1 times the y resolution for best result
	
	resolutionX = 384		# a multiple of the tilesize for more efficient map drawing
	resolutionY = 288		# a multiple of the tilesize for more efficient map drawing
	
	canvasBufferSize = 2	# at least 2 at most 3