tilesize = 32 
modsPath = '/mods'
mapsPath = '/maps'
tilesetsPath = '/tilesets'
gameStatesPath = '/gameStates'

[displayMode]
	displayWidth = 800
	displayHeight = 600
	resolutionX = 400
	resolutionY = 300
	canvasBufferSize = 2